Entities\Person:
    type: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
      name: discr
      type: string
    discriminatorMap:
      person: Person
      employee: Employee
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        adate:
            type: date